import React, { useState } from 'react';
import { X, Calculator, IndianRupee, HardHat, FileText, Download, CheckCircle, Sliders } from 'lucide-react';
import { calculateConstructionBOQ, CONSTRUCTION_PACKAGES } from '../services/constructionCostEstimator';

export default function CivilEstimatorModal({ isOpen, onClose, layout }) {
  if (!isOpen) return null;

  const builtUpArea = layout?.builtUpArea || layout?.usedArea || 1200;
  const [packageType, setPackageType] = useState('standard');
  const [customRate, setCustomRate] = useState(CONSTRUCTION_PACKAGES.standard.ratePerSqFt);
  const [currencySymbol, setCurrencySymbol] = useState('₹');

  const boq = calculateConstructionBOQ(builtUpArea, packageType, customRate);

  const handlePackageChange = (type) => {
    setPackageType(type);
    setCustomRate(CONSTRUCTION_PACKAGES[type].ratePerSqFt);
  };

  const handleDownloadReport = () => {
    const lines = [
      `CIVIL CONSTRUCTION BILL OF QUANTITIES (BOQ) & COST ESTIMATE`,
      `Project: ${layout.projectName || 'Building Layout'}`,
      `Total Built-Up Area: ${builtUpArea} sq.ft`,
      `Quality Specification: ${CONSTRUCTION_PACKAGES[packageType]?.name || 'Custom'} (${currencySymbol}${customRate}/sq.ft)`,
      `Total Estimated Cost: ${currencySymbol}${boq.totalCost.toLocaleString()} (${currencySymbol}${boq.totalCostInLakhs} Lakhs)`,
      `------------------------------------------------------------`,
      `ITEM / MATERIAL | QUANTITY | ESTIMATED COST`,
      ...boq.materialBreakdown.map(m => `${m.item} | ${m.quantity} | ${currencySymbol}${m.cost.toLocaleString()}`),
      `------------------------------------------------------------`,
      `Generated by AI House Planner Civil Architecture Engine (NBC 2016 / IS 456)`
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `BOQ_Cost_Estimate_${builtUpArea}sqft.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 backdrop-blur-sm p-4 overflow-y-auto">
      <div className="bg-white border border-slate-200 rounded-3xl shadow-2xl w-full max-w-3xl overflow-hidden animate-in fade-in zoom-in-95 duration-150">
        
        {/* Header */}
        <div className="bg-slate-900 text-white p-5 flex items-center justify-between border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-amber-500 flex items-center justify-center text-slate-950 font-black shadow-md">
              <HardHat className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-base font-black tracking-tight">Civil BOQ & Construction Cost Estimator</h2>
              <p className="text-xs text-slate-400 font-mono">IS 456:2000 • CPWD Material Coefficient Rates</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="p-6 space-y-6 max-h-[75vh] overflow-y-auto">
          
          {/* Package Selection Cards */}
          <div className="grid grid-cols-3 gap-3">
            {Object.entries(CONSTRUCTION_PACKAGES).map(([key, pkg]) => {
              const active = packageType === key;
              return (
                <button
                  key={key}
                  onClick={() => handlePackageChange(key)}
                  className={`p-3.5 rounded-2xl border text-left transition-all relative ${
                    active ? 'border-amber-500 bg-amber-50/50 shadow-sm ring-2 ring-amber-500/20' : 'border-slate-200 hover:border-slate-300 bg-white'
                  }`}
                >
                  <div className="flex items-center justify-between mb-1">
                    <span className="font-extrabold text-xs text-slate-900">{pkg.name}</span>
                    {active && <CheckCircle className="w-4 h-4 text-amber-600" />}
                  </div>
                  <div className="text-sm font-black text-slate-900 font-mono">
                    {currencySymbol}{pkg.ratePerSqFt} <span className="text-[10px] text-slate-500 font-normal">/ sq.ft</span>
                  </div>
                  <p className="text-[10px] text-slate-500 mt-1 line-clamp-2 leading-relaxed">{pkg.desc}</p>
                </button>
              );
            })}
          </div>

          {/* Rate Fine Tuning */}
          <div className="bg-slate-50 border border-slate-200 rounded-2xl p-4 flex flex-wrap items-center justify-between gap-4">
            <div>
              <div className="text-xs font-bold text-slate-700">Custom Rate Adjustment</div>
              <div className="text-[11px] text-slate-500">Built-Up Area: <span className="font-bold text-slate-900">{builtUpArea} sq.ft</span></div>
            </div>
            <div className="flex items-center gap-3">
              <input
                type="range"
                min="1000"
                max="4000"
                step="50"
                value={customRate}
                onChange={(e) => setCustomRate(Number(e.target.value))}
                className="w-40 accent-amber-500 cursor-pointer"
              />
              <div className="flex items-center bg-white border border-slate-300 px-3 py-1.5 rounded-xl font-mono text-xs font-bold text-slate-900 shadow-inner">
                {currencySymbol}
                <input
                  type="number"
                  value={customRate}
                  onChange={(e) => setCustomRate(Number(e.target.value))}
                  className="w-16 outline-none bg-transparent ml-1"
                />
                <span className="text-[10px] text-slate-400 font-normal">/sq.ft</span>
              </div>
            </div>
          </div>

          {/* Total Cost Display Banner */}
          <div className="bg-gradient-to-br from-slate-900 to-slate-800 text-white rounded-2xl p-5 shadow-lg flex items-center justify-between">
            <div>
              <div className="text-[11px] uppercase tracking-widest text-amber-400 font-bold">Estimated Turnkey Construction Cost</div>
              <div className="text-2xl sm:text-3xl font-black font-mono mt-1 text-white">
                {currencySymbol}{boq.totalCost.toLocaleString()}
                <span className="text-sm font-bold text-slate-300 ml-2">({currencySymbol}{boq.totalCostInLakhs} Lakhs)</span>
              </div>
            </div>
            <div className="text-right text-xs text-slate-300 font-mono hidden sm:block">
              <div>Materials: <strong className="text-white">{currencySymbol}{boq.materialsTotal.toLocaleString()}</strong></div>
              <div>Labor & Workforce: <strong className="text-white">{currencySymbol}{boq.laborCost.toLocaleString()}</strong></div>
            </div>
          </div>

          {/* Detailed BOQ Table */}
          <div className="border border-slate-200 rounded-2xl overflow-hidden">
            <div className="bg-slate-100 px-4 py-2.5 border-b border-slate-200 flex items-center justify-between text-xs font-bold text-slate-700">
              <span>Material & Labor Breakdown</span>
              <span>Estimated Value</span>
            </div>
            <div className="divide-y divide-slate-100">
              {boq.materialBreakdown.map((item, idx) => (
                <div key={idx} className="px-4 py-2.5 flex items-center justify-between text-xs hover:bg-slate-50 transition">
                  <div>
                    <div className="font-bold text-slate-800">{item.item}</div>
                    <div className="text-[11px] text-slate-500 font-mono">{item.quantity}</div>
                  </div>
                  <div className="text-right">
                    <div className="font-bold text-slate-900 font-mono">{currencySymbol}{item.cost.toLocaleString()}</div>
                    <div className="text-[10px] text-slate-400 font-mono">{item.sharePct}% of total</div>
                  </div>
                </div>
              ))}
            </div>
          </div>

        </div>

        {/* Footer */}
        <div className="bg-slate-50 border-t border-slate-200 p-4 px-6 flex items-center justify-between">
          <span className="text-xs text-slate-500 font-medium hidden sm:inline">
            Estimates comply with IS 456 & CPWD Schedule of Rates (DSR).
          </span>
          <div className="flex items-center gap-2">
            <button
              onClick={handleDownloadReport}
              className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs rounded-xl flex items-center gap-1.5 shadow-sm transition"
            >
              <Download className="w-4 h-4" /> Download BOQ (.txt)
            </button>
            <button
              onClick={onClose}
              className="px-4 py-2 bg-white hover:bg-slate-100 border border-slate-300 text-slate-700 font-bold text-xs rounded-xl transition"
            >
              Close
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
