/**
 * BIM & 3D Architectural Model Export Utilities
 * Generates standard Wavefront OBJ files and BIM JSON exports.
 */

import * as THREE from 'three';

/**
 * Exports a Three.js Group/Scene or BIM model to standard Wavefront OBJ format
 */
export function exportThreeSceneToObj(sceneOrGroup, filename = 'building_model_bim.obj') {
  if (!sceneOrGroup) return;

  let output = '# Autodesk Revit / BIM Compatible 3D Model Export\n';
  output += `# Generated by AI House Planner Architectural BIM Engine\n`;
  output += `# Units: Feet / Metres (as defined in project)\n\n`;

  let vertexOffset = 1;
  let normalOffset = 1;

  sceneOrGroup.traverse((child) => {
    if (child.isMesh && child.geometry) {
      const geometry = child.geometry.isBufferGeometry ? child.geometry.clone() : new THREE.BufferGeometry().fromGeometry(child.geometry);
      
      // Apply world transform
      child.updateWorldMatrix(true, false);
      geometry.applyMatrix4(child.matrixWorld);

      const positions = geometry.attributes.position;
      const normals = geometry.attributes.normal;
      const indices = geometry.index;

      if (!positions) return;

      const objName = (child.name || child.userData?.type || 'ArchitecturalElement').replace(/\s+/g, '_');
      output += `o ${objName}\n`;

      // Vertices
      for (let i = 0; i < positions.count; i++) {
        const x = positions.getX(i);
        const y = positions.getY(i);
        const z = positions.getZ(i);
        output += `v ${x.toFixed(4)} ${y.toFixed(4)} ${z.toFixed(4)}\n`;
      }

      // Normals
      if (normals) {
        for (let i = 0; i < normals.count; i++) {
          const nx = normals.getX(i);
          const ny = normals.getY(i);
          const nz = normals.getZ(i);
          output += `vn ${nx.toFixed(4)} ${ny.toFixed(4)} ${nz.toFixed(4)}\n`;
        }
      }

      // Faces
      if (indices) {
        for (let i = 0; i < indices.count; i += 3) {
          const a = indices.getX(i) + vertexOffset;
          const b = indices.getX(i + 1) + vertexOffset;
          const c = indices.getX(i + 2) + vertexOffset;

          if (normals) {
            output += `f ${a}//${a} ${b}//${b} ${c}//${c}\n`;
          } else {
            output += `f ${a} ${b} ${c}\n`;
          }
        }
      } else {
        for (let i = 0; i < positions.count; i += 3) {
          const a = i + vertexOffset;
          const b = i + 1 + vertexOffset;
          const c = i + 2 + vertexOffset;

          if (normals) {
            output += `f ${a}//${a} ${b}//${b} ${c}//${c}\n`;
          } else {
            output += `f ${a} ${b} ${c}\n`;
          }
        }
      }

      vertexOffset += positions.count;
      if (normals) normalOffset += normals.count;
      output += '\n';
    }
  });

  const blob = new Blob([output], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Exports complete BIM Model JSON
 */
export function exportBimJson(bimModel, filename = 'building_bim_model.json') {
  const jsonStr = JSON.stringify(bimModel, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Captures high-res screenshot from WebGL canvas
 */
export function capture3DScreenshot(renderer, filename = 'building_3d_render.png') {
  if (!renderer || !renderer.domElement) return;
  const dataUrl = renderer.domElement.toDataURL('image/png');
  const link = document.createElement('a');
  link.href = dataUrl;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
